#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#polybar状态栏
$HOME/.config/polybar/bspwm.sh
#$HOME/.config/polybar/launch.sh --docky


#Fcitx 输入法
fcitx&

# 设置主屏幕以及副屏幕旋转
#xrandr --output HDMI-A-0 --left-of DisplayPort-0 --mode "1920x1080" --output DisplayPort-0 --primary --mode "1920x1080"
xrandr --output DisplayPort-0 --primary --mode "1920x1080" --output HDMI-A-0 --left-of     DisplayPort-0 --mode "1920x1080" --rotate right

#设置多屏幕
#bspc monitor DisplayPort-0 -d 1 2 3 4
#bspc monitor HDMI3 -d 1 2 3 4
bspc monitor HDMI-A-0 -d 1 2 3 4 5 

#设置鼠标速度
xinput --set-prop "pointer:Razer Razer Basilisk Essential" "libinput Accel Speed" -0.8

#设置屏幕壁纸
feh --randomize --bg-scale ~/.config/wallpapers/*

#窗口透明
compton -b&

#网络组件
nm-applet&

#声音组件
volumeicon&

#蓝牙组件
blueman-applet&

#不显示X型光标
xsetroot -cursor_name left_ptr &

##################################
# bspwm设置
############################

#设置窗口边框及边距
bspc config border_width        6
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#颜色设置
bspc config normal_border_color     \#88C0D0
bspc config active_border_color     \#285577
bspc config focused_border_color    \#0099ff
